services:
  frontend:
    image: game_frontend
    container_name: game_frontend
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - frontend

networks:
  frontend:
    name: ngrok_network
    external: true
